on:
  workflow_dispatch:
  # push:
    # branches:
      # - master

name: Deploy the website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 20         
      - name: Install npm packages
        run: npm install
      - name: Build Tina CMS
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        run: npx tinacms build          
      - name: Build to _site
        run: npm run deploy
      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_HOST }}
          local_path: './_site/*'
          remote_path: '${{ secrets.DESTINATION_PATH }}'
          sftp_only: true
          password: ${{ secrets.SFTP_PW }}
